config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'static_pages#index'
  get 'users/:username', to: 'users#show', as: :profile
  resources :posts
  get 'blog', to: 'posts#index', as: :blog
  namespace :admin do
    resources :posts, only: [:index, :create, :show, :edit, :update, :delete]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  paginates_per 4

  scope :approved, -> { where(:postreview => false) }
  scope :pending, -> { where(:postreview => true) }

  belongs_to :user
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action do
    redirect_to :new_user_session_path unless current_user && current_user.admin?
  end

  def index
    @posts = Post.pending.all
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :postreview)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  before_action :check_if_admin!, :only => [:update]

  def index
    @posts = Post.approved.page params[:page]
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    redirect_to blog_path
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    @post.update_attributes(post_params)
    @post.update(postreview: false)
    redirect_to blog_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :postreview, :slug)
  end

  def check_if_admin!
    redirect_to :new_user_session_path unless current_user && current_user.admin?
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/edit.html.slim
section class="standard-boxes col-md-6 col-md-offset-3"
  h1 Edit post
  = simple_form_for @post do |f|
    = f.input :title
    br
    = f.input :body, as: :wysihtml5
    br
    = f.submit 'Approve post', :postreview => false, class: 'btn btn-primary'

app/views/admin/posts/index.html.slim
- require 'sanitize'

- @posts.each do |post|
    section class="blog-show col-md-6 col-md-offset-3"
      h2 #{post.title}
      h5 by #{post.user.firstname} #{post.user.lastname}
      h4 class="body-format"
        == Sanitize.fragment(post.body,
          :elements => ['b', 'br', 'a', 'i', 'u', 'ul', 'ol', 'li', 'blockquote', 'div', 'h2', 'h3', 'h4', 'h5', 'h6' 'br', 'img' ],
          :attributes => {'a' => ['href', 'title', 'target']},
          :protocols => {'a' => {'href' => ['http', 'https']}},
          :whitespace_elements => {'br' => { :before => "\n", :after => "\n"}, 'div' => { :before => "\n", :after => "\n" }, 'p' => { :before => "\n", :after => "\n" }})
      br
      == link_to "Edit post", edit_admin_post_path(post), class: 'btn btn-primary'

section class="footer col-md-6 col-md-offset-3"
  == link_to "Back home", root_path, class: "btn btn-primary btn-lg"