config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'static_pages#index'
  get 'users/:username', to: 'users#show', as: :profile
  resources :posts
  get 'blog', to: 'posts#index', as: :blog
  namespace :admin do
    resources :posts, only: [:index, :create, :show, :edit, :update, :delete]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  paginates_per 4

  scope :approved, -> { where(:postreview => false) }
  scope :pending, -> { where(:postreview => true) }

  belongs_to :user
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action do
    redirect_to :new_user_session_path unless current_user && current_user.admin?
  end

  def index
    @posts = Post.pending.all
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :postreview)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  before_action :check_if_admin!, :only => [:update]

  def index
    @posts = Post.approved.page params[:page]
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    redirect_to blog_path
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    @post.update_attributes(post_params)
    @post.update(postreview: false)
    redirect_to blog_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :postreview, :slug)
  end

  def check_if_admin!
    redirect_to :new_user_session_path unless current_user && current_user.admin?
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

var disqus_config = function () {
    this.page.url = '<%= url_for([@post, {only_path: false}]) %>';
    this.page.identifier = '<%= @post.id %>';
    this.page.title = '<%= @post.title %>';
};

(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = '//nashville-nsa.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>

<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/index.html.slim
- require 'sanitize'

section class="header"
  div class="header-left col-md-3  col-md-offset-1 col-xs-10 col-xs-offset-1"
    h1 Catch up with us
  = link_to "Submit a post", new_post_path, class: "header-right col-md-2 col-md-offset-4 col-xs-5 col-xs-offset-3"
  div class="clearfix"

section class="blog col-xs-10 col-xs-offset-1"
  - @posts.in_groups_of(2) do |post1, post2|
    div class="row posts-index"
      div class="col-md-5 col-xs-10 col-xs-offset-1 post-margin posts-style"
        h2 #{post1.title}
        h4 class="by-line-index" by #{post1.user.firstname} #{post1.user.lastname}
        h4 class="body-format"
          - excerpt = Sanitize.fragment(post1.body,
            :elements => ['b', 'br', 'a', 'i', 'u', 'ul', 'ol', 'li', 'blockquote', 'div', 'h4', 'h5', 'h6' 'br', 'img' ],
            :attributes => {'a' => ['href', 'title', 'target']},
            :protocols => {'a' => {'href' => ['http', 'https']}},
            :whitespace_elements => {'br' => { :before => "\n", :after => "\n"}, 'div' => { :before => "\n", :after => "\n" }, 'p' => { :before => "\n", :after => "\n" }})
          == truncate(excerpt, length: 400, escape: false)
          br
          br
          == link_to 'Read more...', post_path(post1), class: 'read-more'
        p class="date" posted on #{post1.created_at.to_time.strftime('%B %d, %Y')}

      - if post2

        div class="col-md-5 col-md-offset-1 col-xs-10 col-xs-offset-1 posts-style"
          h2 #{post2.title}
          h4 class="by-line-index" by #{post2.user.firstname} #{post2.user.lastname}
          h4 class="body-format"
            - excerpt = Sanitize.fragment(post2.body,
              :elements => ['b', 'br', 'a', 'i', 'u', 'ul', 'ol', 'li', 'blockquote', 'div', 'h2', 'h3', 'h4', 'h5', 'h6' 'br', 'img' ],
              :attributes => {'a' => ['href', 'title', 'target']},
              :protocols => {'a' => {'href' => ['http', 'https']}},
              :whitespace_elements => {'br' => { :before => "\n", :after => "\n"}, 'div' => { :before => "\n", :after => "\n" }, 'p' => { :before => "\n", :after => "\n" }})
            == truncate(excerpt, length: 400, escape: false)
            br
            br
            == link_to 'Read more...', post_path(post2), class: 'read-more'
          p class="date" posted on #{post2.created_at.to_time.strftime('%B %d, %Y')}

  div class="col-sm-6 col-sm-offset-5 col-xs-10 col-xs-offset-1"
    == paginate @posts

app/views/posts/new.html.slim
section class="standard-boxes col-md-6 col-md-offset-3"
  h1 Share some thoughts with us
  h4 Before making a post submission, please submit your idea at a NSA meeting for approval. If you don't, your post will not be approved. Thank you!
  span class="red" NOTE: 
  p class="inline" Do not refresh the page or your content will be lost.
  br
  = simple_form_for @post do |f|
    = f.input :title
    br
    = f.input :body, as: :wysihtml5
    br
    = f.submit 'Submit for approval', :class => 'btn btn-primary'

  br
  p class="approval-info" data-toggle="tooltip" data-placement="right" data-title="Mostly we'll check for grammar, typos, and fix formatting. If we ever think we're changing your voice or content, we'll run the revised post by you first. :)" What is approval?

app/views/posts/show.html.slim
- require 'sanitize'

section class="blog-show col-md-6 col-md-offset-3"
  h2 #{@post.title}
  h5 class="by-line" by #{@post.user.firstname} #{@post.user.lastname}
  h6 class="body-show"
    == Sanitize.fragment(@post.body,
      :elements => ['b', 'br', 'a', 'i', 'u', 'div', 'h3', 'h4', 'h5', 'h6' 'br', 'img'],
      :attributes => {'a' => ['href', 'title', 'target']},
      :protocols => {'a' => {'href' => ['http', 'https']}},
      :whitespace_elements => {'br' => { :before => "\n", :after => "\n"}, 'div' => { :before => "\n", :after => "\n" }, 'p' => { :before => "\n", :after => "\n" }})
  p class="closing" posted on #{@post.created_at.to_time.strftime('%B %d, %Y')}

  == render 'disqus'