config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'static_pages#index'
  get 'users/:username', to: 'users#show', as: :profile
  resources :posts
  get 'blog', to: 'posts#index', as: :blog
  namespace :admin do
    resources :posts, only: [:index, :create, :show, :edit, :update, :delete]
  end

end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title Nashville Stuttering Association (NSA)
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="description" content="The Nashville chapter of the National Stuttering Association aims to bring together people who stutter and those who support them (including speech-language pathologists [SLPs]) in monthly meetings."
    meta name="keywords" content="stuttering, nashville, stutter, national stuttering association, slp, speech-language pathologist"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

  body

    nav.navbar.navbar-default role="navigation"
      .container-fluid
        /! Brand and toggle get grouped for better mobile display
        .navbar-header
          button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          div class="navbar-brand"
            = link_to "Nashville NSA", root_path
        /! Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li
                = link_to "My profile", profile_path(current_user.username), class: "nav-style"
              li
                = link_to "Blog", blog_path, class: "nav-style"
              li
                = link_to "Log out", destroy_user_session_path, method: :delete
            - else
              li class="sign-in"
                span class="nav-span"
                  = link_to "Create an account", new_user_registration_path, class: "nav-style span-child"
              li
                = link_to "Log in", new_user_session_path

    - if notice.present?
      p class="alert alert-info"
        = notice
    - if alert.present?
      p class="alert alert-danger"
        = alert

    == yield